#pragma once

#include <inttypes.h>
#include <unordered_map>

enum Opcode : uint8_t
{
	ADD_A = 0x87,
	ADD_B = 0x80,
	ADD_C = 0x81,
	ADD_D = 0x82,
	ADD_E = 0x83,
	ADD_H = 0x84,
	ADD_L = 0x85,
	ADD_M = 0x86,
	ADI_d8 = 0xC6,
	ADC_A = 0x8F,
	ADC_B = 0x88,
	ADC_C = 0x89,
	ADC_D = 0x8A,
	ADC_E = 0x8B,
	ADC_H = 0x8C,
	ADC_L = 0x8D,
	ADC_M = 0x8E,
	ACI_d8 = 0xCE,
	ANA_A = 0xA7,
	ANA_B = 0xA0,
	ANA_C = 0xA1,
	ANA_D = 0xA2,
	ANA_E = 0xA3,
	ANA_H = 0xA4,
	ANA_L = 0xA5,
	ANA_M = 0xA6,
	ANI_d8 = 0xE6,
	CALL_a16 = 0xCD,
	CZ_a16 = 0xCC,
	CNZ_a16 = 0xC4,
	CP_a16 = 0xF4,
	CM_a16 = 0xFC,
	CC_a16 = 0xDC,
	CNC_a16 = 0xD4,
	CPE_a16 = 0xEC,
	CPO_a16 = 0xE4,
	CMA = 0x2F,
	CMC = 0x3F,
	CMP_A = 0xBF,
	CMP_B = 0xB8,
	CMP_C = 0xB9,
	CMP_D = 0xBA,
	CMP_E = 0xBB,
	CMP_H = 0xBC,
	CMP_L = 0xBD,
	CMP_M = 0xBE,
	CPI_d8 = 0xFE,
	DAA = 0x27,
	DAD_B = 0x09,
	DAD_D = 0x19,
	DAD_H = 0x29,
	DAD_SP = 0x39,
	DCR_A = 0x3D,
	DCR_B = 0x05,
	DCR_C = 0x0D,
	DCR_D = 0x15,
	DCR_E = 0x1D,
	DCR_H = 0x25,
	DCR_L = 0x2D,
	DCR_M = 0x35,
	DCX_B = 0x0B,
	DCX_D = 0x1B,
	DCX_H = 0x2B,
	DCX_SP = 0x3B,
	DI = 0xF3,
	EI = 0xFB,
	HLT = 0x76,
	IN_pp = 0xDB,
	INR_A = 0x3C,
	INR_B = 0x04,
	INR_C = 0x0C,
	INR_D = 0x14,
	INR_E = 0x1C,
	INR_H = 0x24,
	INR_L = 0x2C,
	INR_M = 0x34,
	INX_B = 0x03,
	INX_D = 0x13,
	INX_H = 0x23,
	INX_SP = 0x33,
	JMP_a16 = 0xC3,
	JZ_a16 = 0xCA,
	JNZ_a16 = 0xC2,
	JP_a16 = 0xF2,
	JM_a16 = 0xFA,
	JC_a16 = 0xDA,
	JNC_a16 = 0xD2,
	JPE_a16 = 0xEA,
	JPO_a16 = 0xE2,
	LDA_a16 = 0x3A,
	LDAX_B = 0x0A,
	LDAX_D = 0x1A,
	LHLD_a16 = 0x2A,
	LXI_B_d16 = 0x01,
	LXI_D_d16 = 0x11,
	LXI_H_d16 = 0x21,
	LXI_SP_d16 = 0x31,
	MOV_A_A = 0x7F,
	MOV_A_B = 0x78,
	MOV_A_C = 0x79,
	MOV_A_D = 0x7A,
	MOV_A_E = 0x7B,
	MOV_A_H = 0x7C,
	MOV_A_L = 0x7D,
	MOV_A_M = 0x7E,
	MOV_B_A = 0x47,
	MOV_B_B = 0x40,
	MOV_B_C = 0x41,
	MOV_B_D = 0x42,
	MOV_B_E = 0x43,
	MOV_B_H = 0x44,
	MOV_B_L = 0x45,
	MOV_B_M = 0x46,
	MOV_C_A = 0x4F,
	MOV_C_B = 0x48,
	MOV_C_C = 0x49,
	MOV_C_D = 0x4A,
	MOV_C_E = 0x4B,
	MOV_C_H = 0x4C,
	MOV_C_L = 0x4D,
	MOV_C_M = 0x4E,
	MOV_D_A = 0x57,
	MOV_D_B = 0x50,
	MOV_D_C = 0x51,
	MOV_D_D = 0x52,
	MOV_D_E = 0x53,
	MOV_D_H = 0x54,
	MOV_D_L = 0x55,
	MOV_D_M = 0x56,
	MOV_E_A = 0x5F,
	MOV_E_B = 0x58,
	MOV_E_C = 0x59,
	MOV_E_D = 0x5A,
	MOV_E_E = 0x5B,
	MOV_E_H = 0x5C,
	MOV_E_L = 0x5D,
	MOV_E_M = 0x5E,
	MOV_H_A = 0x67,
	MOV_H_B = 0x60,
	MOV_H_C = 0x61,
	MOV_H_D = 0x62,
	MOV_H_E = 0x63,
	MOV_H_H = 0x64,
	MOV_H_L = 0x65,
	MOV_H_M = 0x66,
	MOV_L_A = 0x6F,
	MOV_L_B = 0x68,
	MOV_L_C = 0x69,
	MOV_L_D = 0x6A,
	MOV_L_E = 0x6B,
	MOV_L_H = 0x6C,
	MOV_L_L = 0x6D,
	MOV_L_M = 0x6E,
	MOV_M_A = 0x77,
	MOV_M_B = 0x70,
	MOV_M_C = 0x71,
	MOV_M_D = 0x72,
	MOV_M_E = 0x73,
	MOV_M_H = 0x74,
	MOV_M_L = 0x75,
	MVI_A_d8 = 0x3E,
	MVI_B_d8 = 0x06,
	MVI_C_d8 = 0x0E,
	MVI_D_d8 = 0x16,
	MVI_E_d8 = 0x1E,
	MVI_H_d8 = 0x26,
	MVI_L_d8 = 0x2E,
	MVI_M_d8 = 0x36,
	NOP = 0x00,
	ORA_A = 0xB7,
	ORA_B = 0xB0,
	ORA_C = 0xB1,
	ORA_D = 0xB2,
	ORA_E = 0xB3,
	ORA_H = 0xB4,
	ORA_L = 0xB5,
	ORA_M = 0xB6,
	ORI_d8 = 0xF6,
	OUT_pp = 0xD3,
	PCHL = 0xE9,
	POP_B = 0xC1,
	POP_D = 0xD1,
	POP_H = 0xE1,
	POP_PSW = 0xF1,
	PUSH_B = 0xC5,
	PUSH_D = 0xD5,
	PUSH_H = 0xE5,
	PUSH_PSW = 0xF5,
	RAL = 0x17,
	RAR = 0x1F,
	RLC = 0x07,
	RRC = 0x0F,
	RIM = 0x20,
	RET = 0xC9,
	RZ = 0xC8,
	RNZ = 0xC0,
	RP = 0xF0,
	RM = 0xF8,
	RC = 0xD8,
	RNC = 0xD0,
	RPE = 0xE8,
	RPO = 0xE0,
	RST_0 = 0xC7,
	RST_1 = 0xCF,
	RST_2 = 0xD7,
	RST_3 = 0xDF,
	RST_4 = 0xE7,
	RST_5 = 0xEF,
	RST_6 = 0xF7,
	RST_7 = 0xFF,
	SIM = 0x30,
	SPHL = 0xF9,
	SHLD_a16 = 0x22,
	STA_a16 = 0x32,
	STAX_B = 0x02,
	STAX_D = 0x12,
	STC = 0x37,
	SUB_A = 0x97,
	SUB_B = 0x90,
	SUB_C = 0x91,
	SUB_D = 0x92,
	SUB_E = 0x93,
	SUB_H = 0x94,
	SUB_L = 0x95,
	SUB_M = 0x96,
	SUI_d8 = 0xD6,
	SBB_A = 0x9F,
	SBB_B = 0x98,
	SBB_C = 0x99,
	SBB_D = 0x9A,
	SBB_E = 0x9B,
	SBB_H = 0x9C,
	SBB_L = 0x9D,
	SBB_M = 0x9E,
	SBI_d8 = 0xDE,
	XCHG = 0xEB,
	XTHL = 0xE3,
	XRA_A = 0xAF,
	XRA_B = 0xA8,
	XRA_C = 0xA9,
	XRA_D = 0xAA,
	XRA_E = 0xAB,
	XRA_H = 0xAC,
	XRA_L = 0xAD,
	XRA_M = 0xAE,
	XRI_d8 = 0xEE,
};

typedef struct
{
	size_t Length;
	const char* Mnemonic;
} OpcodeInfo_t;

static std::unordered_map<Opcode, OpcodeInfo_t> OpcodeInfo = {
	{ ADD_A, { 1, "ADD A" } },
	{ ADD_B, { 1, "ADD B" } },
	{ ADD_C, { 1, "ADD C" } },
	{ ADD_D, { 1, "ADD D" } },
	{ ADD_E, { 1, "ADD E" } },
	{ ADD_H, { 1, "ADD H" } },
	{ ADD_L, { 1, "ADD L" } },
	{ ADD_M, { 1, "ADD M" } },
	{ ADI_d8, { 2, "ADI d8" } },
	{ ADC_A, { 1, "ADC A" } },
	{ ADC_B, { 1, "ADC B" } },
	{ ADC_C, { 1, "ADC C" } },
	{ ADC_D, { 1, "ADC D" } },
	{ ADC_E, { 1, "ADC E" } },
	{ ADC_H, { 1, "ADC H" } },
	{ ADC_L, { 1, "ADC L" } },
	{ ADC_M, { 1, "ADC M" } },
	{ ACI_d8, { 2, "ACI d8" } },
	{ ANA_A, { 1, "ANA A" } },
	{ ANA_B, { 1, "ANA B" } },
	{ ANA_C, { 1, "ANA C" } },
	{ ANA_D, { 1, "ANA D" } },
	{ ANA_E, { 1, "ANA E" } },
	{ ANA_H, { 1, "ANA H" } },
	{ ANA_L, { 1, "ANA L" } },
	{ ANA_M, { 1, "ANA M" } },
	{ ANI_d8, { 2, "ANI d8" } },
	{ CALL_a16, { 3, "CALL a16" } },
	{ CZ_a16, { 3, "CZ a16" } },
	{ CNZ_a16, { 3, "CNZ a16" } },
	{ CP_a16, { 3, "CP a16" } },
	{ CM_a16, { 3, "CM a16" } },
	{ CC_a16, { 3, "CC a16" } },
	{ CNC_a16, { 3, "CNC a16" } },
	{ CPE_a16, { 3, "CPE a16" } },
	{ CPO_a16, { 3, "CPO a16" } },
	{ CMA, { 1, "CMA" } },
	{ CMC, { 1, "CMC" } },
	{ CMP_A, { 1, "CMP A" } },
	{ CMP_B, { 1, "CMP B" } },
	{ CMP_C, { 1, "CMP C" } },
	{ CMP_D, { 1, "CMP D" } },
	{ CMP_E, { 1, "CMP E" } },
	{ CMP_H, { 1, "CMP H" } },
	{ CMP_L, { 1, "CMP L" } },
	{ CMP_M, { 1, "CMP M" } },
	{ CPI_d8, { 2, "CPI d8" } },
	{ DAA, { 1, "DAA" } },
	{ DAD_B, { 1, "DAD B" } },
	{ DAD_D, { 1, "DAD D" } },
	{ DAD_H, { 1, "DAD H" } },
	{ DAD_SP, { 1, "DAD SP" } },
	{ DCR_A, { 1, "DCR A" } },
	{ DCR_B, { 1, "DCR B" } },
	{ DCR_C, { 1, "DCR C" } },
	{ DCR_D, { 1, "DCR D" } },
	{ DCR_E, { 1, "DCR E" } },
	{ DCR_H, { 1, "DCR H" } },
	{ DCR_L, { 1, "DCR L" } },
	{ DCR_M, { 1, "DCR M" } },
	{ DCX_B, { 1, "DCX B" } },
	{ DCX_D, { 1, "DCX D" } },
	{ DCX_H, { 1, "DCX H" } },
	{ DCX_SP, { 1, "DCX SP" } },
	{ DI, { 1, "DI" } },
	{ EI, { 1, "EI" } },
	{ HLT, { 1, "HLT" } },
	{ IN_pp, { 2, "IN pp" } },
	{ INR_A, { 1, "INR A" } },
	{ INR_B, { 1, "INR B" } },
	{ INR_C, { 1, "INR C" } },
	{ INR_D, { 1, "INR D" } },
	{ INR_E, { 1, "INR E" } },
	{ INR_H, { 1, "INR H" } },
	{ INR_L, { 1, "INR L" } },
	{ INR_M, { 1, "INR M" } },
	{ INX_B, { 1, "INX B" } },
	{ INX_D, { 1, "INX D" } },
	{ INX_H, { 1, "INX H" } },
	{ INX_SP, { 1, "INX SP" } },
	{ JMP_a16, { 3, "JMP a16" } },
	{ JZ_a16, { 3, "JZ a16" } },
	{ JNZ_a16, { 3, "JNZ a16" } },
	{ JP_a16, { 3, "JP a16" } },
	{ JM_a16, { 3, "JM a16" } },
	{ JC_a16, { 3, "JC a16" } },
	{ JNC_a16, { 3, "JNC a16" } },
	{ JPE_a16, { 3, "JPE a16" } },
	{ JPO_a16, { 3, "JPO a16" } },
	{ LDA_a16, { 3, "LDA a16" } },
	{ LDAX_B, { 1, "LDAX B" } },
	{ LDAX_D, { 1, "LDAX D" } },
	{ LHLD_a16, { 3, "LHLD a16" } },
	{ LXI_B_d16, { 3, "LXI B,  d16" } },
	{ LXI_D_d16, { 3, "LXI D,  d16" } },
	{ LXI_H_d16, { 3, "LXI H,  d16" } },
	{ LXI_SP_d16, { 3, "LXI SP,  d16" } },
	{ MOV_A_A, { 1, "MOV A, A" } },
	{ MOV_A_B, { 1, "MOV A, B" } },
	{ MOV_A_C, { 1, "MOV A, C" } },
	{ MOV_A_D, { 1, "MOV A, D" } },
	{ MOV_A_E, { 1, "MOV A, E" } },
	{ MOV_A_H, { 1, "MOV A, H" } },
	{ MOV_A_L, { 1, "MOV A, L" } },
	{ MOV_A_M, { 1, "MOV A, M" } },
	{ MOV_B_A, { 1, "MOV B, A" } },
	{ MOV_B_B, { 1, "MOV B, B" } },
	{ MOV_B_C, { 1, "MOV B, C" } },
	{ MOV_B_D, { 1, "MOV B, D" } },
	{ MOV_B_E, { 1, "MOV B, E" } },
	{ MOV_B_H, { 1, "MOV B, H" } },
	{ MOV_B_L, { 1, "MOV B, L" } },
	{ MOV_B_M, { 1, "MOV B, M" } },
	{ MOV_C_A, { 1, "MOV C, A" } },
	{ MOV_C_B, { 1, "MOV C, B" } },
	{ MOV_C_C, { 1, "MOV C, C" } },
	{ MOV_C_D, { 1, "MOV C, D" } },
	{ MOV_C_E, { 1, "MOV C, E" } },
	{ MOV_C_H, { 1, "MOV C, H" } },
	{ MOV_C_L, { 1, "MOV C, L" } },
	{ MOV_C_M, { 1, "MOV C, M" } },
	{ MOV_D_A, { 1, "MOV D, A" } },
	{ MOV_D_B, { 1, "MOV D, B" } },
	{ MOV_D_C, { 1, "MOV D, C" } },
	{ MOV_D_D, { 1, "MOV D, D" } },
	{ MOV_D_E, { 1, "MOV D, E" } },
	{ MOV_D_H, { 1, "MOV D, H" } },
	{ MOV_D_L, { 1, "MOV D, L" } },
	{ MOV_D_M, { 1, "MOV D, M" } },
	{ MOV_E_A, { 1, "MOV E, A" } },
	{ MOV_E_B, { 1, "MOV E, B" } },
	{ MOV_E_C, { 1, "MOV E, C" } },
	{ MOV_E_D, { 1, "MOV E, D" } },
	{ MOV_E_E, { 1, "MOV E, E" } },
	{ MOV_E_H, { 1, "MOV E, H" } },
	{ MOV_E_L, { 1, "MOV E, L" } },
	{ MOV_E_M, { 1, "MOV E, M" } },
	{ MOV_H_A, { 1, "MOV H, A" } },
	{ MOV_H_B, { 1, "MOV H, B" } },
	{ MOV_H_C, { 1, "MOV H, C" } },
	{ MOV_H_D, { 1, "MOV H, D" } },
	{ MOV_H_E, { 1, "MOV H, E" } },
	{ MOV_H_H, { 1, "MOV H, H" } },
	{ MOV_H_L, { 1, "MOV H, L" } },
	{ MOV_H_M, { 1, "MOV H, M" } },
	{ MOV_L_A, { 1, "MOV L, A" } },
	{ MOV_L_B, { 1, "MOV L, B" } },
	{ MOV_L_C, { 1, "MOV L, C" } },
	{ MOV_L_D, { 1, "MOV L, D" } },
	{ MOV_L_E, { 1, "MOV L, E" } },
	{ MOV_L_H, { 1, "MOV L, H" } },
	{ MOV_L_L, { 1, "MOV L, L" } },
	{ MOV_L_M, { 1, "MOV L, M" } },
	{ MOV_M_A, { 1, "MOV M, A" } },
	{ MOV_M_B, { 1, "MOV M, B" } },
	{ MOV_M_C, { 1, "MOV M, C" } },
	{ MOV_M_D, { 1, "MOV M, D" } },
	{ MOV_M_E, { 1, "MOV M, E" } },
	{ MOV_M_H, { 1, "MOV M, H" } },
	{ MOV_M_L, { 1, "MOV M, L" } },
	{ MVI_A_d8, { 2, "MVI A, d8" } },
	{ MVI_B_d8, { 2, "MVI B, d8" } },
	{ MVI_C_d8, { 2, "MVI C, d8" } },
	{ MVI_D_d8, { 2, "MVI D, d8" } },
	{ MVI_E_d8, { 2, "MVI E, d8" } },
	{ MVI_H_d8, { 2, "MVI H, d8" } },
	{ MVI_L_d8, { 2, "MVI L, d8" } },
	{ MVI_M_d8, { 2, "MVI M, d8" } },
	{ NOP, { 1, "NOP" } },
	{ ORA_A, { 1, "ORA A" } },
	{ ORA_B, { 1, "ORA B" } },
	{ ORA_C, { 1, "ORA C" } },
	{ ORA_D, { 1, "ORA D" } },
	{ ORA_E, { 1, "ORA E" } },
	{ ORA_H, { 1, "ORA H" } },
	{ ORA_L, { 1, "ORA L" } },
	{ ORA_M, { 1, "ORA M" } },
	{ ORI_d8, { 2, "ORI d8" } },
	{ OUT_pp, { 2, "OUT pp" } },
	{ PCHL, { 1, "PCHL" } },
	{ POP_B, { 1, "POP B" } },
	{ POP_D, { 1, "POP D" } },
	{ POP_H, { 1, "POP H" } },
	{ POP_PSW, { 1, "POP PSW" } },
	{ PUSH_B, { 1, "PUSH B" } },
	{ PUSH_D, { 1, "PUSH D" } },
	{ PUSH_H, { 1, "PUSH H" } },
	{ PUSH_PSW, { 1, "PUSH PSW" } },
	{ RAL, { 1, "RAL" } },
	{ RAR, { 1, "RAR" } },
	{ RLC, { 1, "RLC" } },
	{ RRC, { 1, "RRC" } },
	{ RIM, { 1, "RIM" } },
	{ RET, { 1, "RET" } },
	{ RZ, { 1, "RZ" } },
	{ RNZ, { 1, "RNZ" } },
	{ RP, { 1, "RP" } },
	{ RM, { 1, "RM" } },
	{ RC, { 1, "RC" } },
	{ RNC, { 1, "RNC" } },
	{ RPE, { 1, "RPE" } },
	{ RPO, { 1, "RPO" } },
	{ RST_0, { 1, "RST0" } },
	{ RST_1, { 1, "RST1" } },
	{ RST_2, { 1, "RST2" } },
	{ RST_3, { 1, "RST3" } },
	{ RST_4, { 1, "RST4" } },
	{ RST_5, { 1, "RST5" } },
	{ RST_6, { 1, "RST6" } },
	{ RST_7, { 1, "RST7" } },
	{ SIM, { 1, "SIM" } },
	{ SPHL, { 1, "SPHL" } },
	{ SHLD_a16, { 3, "SHLD a16" } },
	{ STA_a16, { 3, "STA a16" } },
	{ STAX_B, { 1, "STAX B" } },
	{ STAX_D, { 1, "STAX D" } },
	{ STC, { 1, "STC" } },
	{ SUB_A, { 1, "SUB A" } },
	{ SUB_B, { 1, "SUB B" } },
	{ SUB_C, { 1, "SUB C" } },
	{ SUB_D, { 1, "SUB D" } },
	{ SUB_E, { 1, "SUB E" } },
	{ SUB_H, { 1, "SUB H" } },
	{ SUB_L, { 1, "SUB L" } },
	{ SUB_M, { 1, "SUB M" } },
	{ SUI_d8, { 2, "SUI d8" } },
	{ SBB_A, { 1, "SBB A" } },
	{ SBB_B, { 1, "SBB B" } },
	{ SBB_C, { 1, "SBB C" } },
	{ SBB_D, { 1, "SBB D" } },
	{ SBB_E, { 1, "SBB E" } },
	{ SBB_H, { 1, "SBB H" } },
	{ SBB_L, { 1, "SBB L" } },
	{ SBB_M, { 1, "SBB M" } },
	{ SBI_d8, { 2, "SBI d8" } },
	{ XCHG, { 1, "XCHG" } },
	{ XTHL, { 1, "XTHL" } },
	{ XRA_A, { 1, "XRA A" } },
	{ XRA_B, { 1, "XRA B" } },
	{ XRA_C, { 1, "XRA C" } },
	{ XRA_D, { 1, "XRA D" } },
	{ XRA_E, { 1, "XRA E" } },
	{ XRA_H, { 1, "XRA H" } },
	{ XRA_L, { 1, "XRA L" } },
	{ XRA_M, { 1, "XRA M" } },
	{ XRI_d8, { 2, "XRI d8" } },
};